global using Avalonia;
global using Avalonia.Data;
global using Avalonia.Markup.Xaml;
global using Avalonia.Metadata;
global using LocalizationManager.Avalonia.Extensions;
global using System.ComponentModel;
global using System.Globalization;
global using System.Reactive.Subjects;
global using System.Reactive.Disposables;
