//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dorisoy.Pan.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dorisoy.Pan.Properties.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于我们 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XXX（Dorisoy） 的本地化字符串。
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        

        
        /// <summary>
        ///   查找类似 语言设置 的本地化字符串。
        /// </summary>
        public static string CurrentAppLanguage {
            get {
                return ResourceManager.GetString("CurrentAppLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更改当前应用程序的语言 的本地化字符串。
        /// </summary>
        public static string CurrentAppLanguageDes {
            get {
                return ResourceManager.GetString("CurrentAppLanguageDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题 的本地化字符串。
        /// </summary>
        public static string CurrentAppTheme {
            get {
                return ResourceManager.GetString("CurrentAppTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更改当前应用程序主题 的本地化字符串。
        /// </summary>
        public static string CurrentAppThemeDes {
            get {
                return ResourceManager.GetString("CurrentAppThemeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 布局方向 的本地化字符串。
        /// </summary>
        public static string CurrentFlowDirection {
            get {
                return ResourceManager.GetString("CurrentFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更改当前应用程序操作布局方向 的本地化字符串。
        /// </summary>
        public static string CurrentFlowDirectionDes {
            get {
                return ResourceManager.GetString("CurrentFlowDirectionDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存储 的本地化字符串。
        /// </summary>
        public static string DocumentPage {
            get {
                return ResourceManager.GetString("DocumentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像 的本地化字符串。
        /// </summary>
        public static string ImagePage {
            get {
                return ResourceManager.GetString("ImagePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前图片存储剩余可用空间 的本地化字符串。
        /// </summary>
        public static string ImageStorageSpaceDes {
            get {
                return ResourceManager.GetString("ImageStorageSpaceDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片存储空间 的本地化字符串。
        /// </summary>
        public static string ImageStorageSpaceTitle {
            get {
                return ResourceManager.GetString("ImageStorageSpaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查 的本地化字符串。
        /// </summary>
        public static string MonitorPage {
            get {
                return ResourceManager.GetString("MonitorPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 患者 的本地化字符串。
        /// </summary>
        public static string PatientPage {
            get {
                return ResourceManager.GetString("PatientPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限 的本地化字符串。
        /// </summary>
        public static string PermissionPage {
            get {
                return ResourceManager.GetString("PermissionPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色 的本地化字符串。
        /// </summary>
        public static string RolePage {
            get {
                return ResourceManager.GetString("RolePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索关键字... 的本地化字符串。
        /// </summary>
        public static string SearchBox {
            get {
                return ResourceManager.GetString("SearchBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string SettingsPage {
            get {
                return ResourceManager.GetString("SettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CaptureManager 视频系统 v2.0.0 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        public static string UserPage {
            get {
                return ResourceManager.GetString("UserPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频 的本地化字符串。
        /// </summary>
        public static string VideoManagePage {
            get {
                return ResourceManager.GetString("VideoManagePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前视频存储剩余可用空间 的本地化字符串。
        /// </summary>
        public static string VideoStorageSpaceDes {
            get {
                return ResourceManager.GetString("VideoStorageSpaceDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频存储空间 的本地化字符串。
        /// </summary>
        public static string VideoStorageSpaceTitle {
            get {
                return ResourceManager.GetString("VideoStorageSpaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎访问Dorisoy! 的本地化字符串。
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
