//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dorisoy.Pan.Language {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dorisoy.Pan.Language.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Access Control Management 的本地化字符串。
        /// </summary>
        internal static string AccessControlManagement {
            get {
                return ResourceManager.GetString("AccessControlManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address: 的本地化字符串。
        /// </summary>
        internal static string Addr {
            get {
                return ResourceManager.GetString("Addr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Remarks 的本地化字符串。
        /// </summary>
        internal static string AddRemarks {
            get {
                return ResourceManager.GetString("AddRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address: 的本地化字符串。
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No. 3, Biyuan Road, Weicheng District, Xianyang City, Shaanxi Province 的本地化字符串。
        /// </summary>
        internal static string AddrInfo {
            get {
                return ResourceManager.GetString("AddrInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aspect Ratio 的本地化字符串。
        /// </summary>
        internal static string AspectRatio {
            get {
                return ResourceManager.GetString("AspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assign Permissions 的本地化字符串。
        /// </summary>
        internal static string AssignPermissions {
            get {
                return ResourceManager.GetString("AssignPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AssignRoles 的本地化字符串。
        /// </summary>
        internal static string AssignRoles {
            get {
                return ResourceManager.GetString("AssignRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backward 的本地化字符串。
        /// </summary>
        internal static string Backward {
            get {
                return ResourceManager.GetString("Backward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basic Configuration 的本地化字符串。
        /// </summary>
        internal static string BasicConfiguration {
            get {
                return ResourceManager.GetString("BasicConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BasicInformation 的本地化字符串。
        /// </summary>
        internal static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Both 的本地化字符串。
        /// </summary>
        internal static string Both {
            get {
                return ResourceManager.GetString("Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checker: 的本地化字符串。
        /// </summary>
        internal static string Checker {
            get {
                return ResourceManager.GetString("Checker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comment: 的本地化字符串。
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CommentComments 的本地化字符串。
        /// </summary>
        internal static string CommentComments {
            get {
                return ResourceManager.GetString("CommentComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CommentTime: 的本地化字符串。
        /// </summary>
        internal static string CommentTime {
            get {
                return ResourceManager.GetString("CommentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dorisoy Medical Equipment Group Co., Ltd 的本地化字符串。
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The company was established in 1965 and is a high-tech enterprise specializing in the research and development, production, manufacturing, and sales of dental medical equipment. The enterprise has always adhered to the road of scientific and technological innovation and development, and established the 13115 Scientific and Technological Innovation Engineering Center in conjunction with Shaanxi University of Science and Technology. The pace of Product development has been significantly accelerated, and succe [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CompanyInfo {
            get {
                return ResourceManager.GetString("CompanyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Telephone: 的本地化字符串。
        /// </summary>
        internal static string Connects {
            get {
                return ResourceManager.GetString("Connects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cookies 的本地化字符串。
        /// </summary>
        internal static string Cookies {
            get {
                return ResourceManager.GetString("Cookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workset CPU usage 的本地化字符串。
        /// </summary>
        internal static string CpuCore {
            get {
                return ResourceManager.GetString("CpuCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VCMS 的本地化字符串。
        /// </summary>
        internal static string CpuCoreTitle {
            get {
                return ResourceManager.GetString("CpuCoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cpu Rate 的本地化字符串。
        /// </summary>
        internal static string CpuRate {
            get {
                return ResourceManager.GetString("CpuRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CpuUseRate 的本地化字符串。
        /// </summary>
        internal static string CpuRateTitle {
            get {
                return ResourceManager.GetString("CpuRateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreationTime: 的本地化字符串。
        /// </summary>
        internal static string CreationTime {
            get {
                return ResourceManager.GetString("CreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creator: 的本地化字符串。
        /// </summary>
        internal static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string CurrentAppLanguage {
            get {
                return ResourceManager.GetString("CurrentAppLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change the language of the current application 的本地化字符串。
        /// </summary>
        internal static string CurrentAppLanguageDes {
            get {
                return ResourceManager.GetString("CurrentAppLanguageDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme 的本地化字符串。
        /// </summary>
        internal static string CurrentAppTheme {
            get {
                return ResourceManager.GetString("CurrentAppTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change the current application theme 的本地化字符串。
        /// </summary>
        internal static string CurrentAppThemeDes {
            get {
                return ResourceManager.GetString("CurrentAppThemeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CurrentDir: 的本地化字符串。
        /// </summary>
        internal static string CurrentDir {
            get {
                return ResourceManager.GetString("CurrentDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flow direction 的本地化字符串。
        /// </summary>
        internal static string CurrentFlowDirection {
            get {
                return ResourceManager.GetString("CurrentFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change the current application operation layout direction 的本地化字符串。
        /// </summary>
        internal static string CurrentFlowDirectionDes {
            get {
                return ResourceManager.GetString("CurrentFlowDirectionDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom Aspect Ratio 的本地化字符串。
        /// </summary>
        internal static string CustomAspectRatio {
            get {
                return ResourceManager.GetString("CustomAspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom Resolution Ratio 的本地化字符串。
        /// </summary>
        internal static string CustomResolutionRatio {
            get {
                return ResourceManager.GetString("CustomResolutionRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Image 的本地化字符串。
        /// </summary>
        internal static string DeleteImage {
            get {
                return ResourceManager.GetString("DeleteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Department 的本地化字符串。
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Document storage statistics 的本地化字符串。
        /// </summary>
        internal static string DocumentCount {
            get {
                return ResourceManager.GetString("DocumentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Documents 的本地化字符串。
        /// </summary>
        internal static string DocumentCountTitle {
            get {
                return ResourceManager.GetString("DocumentCountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Document Management 的本地化字符串。
        /// </summary>
        internal static string DocumentManagement {
            get {
                return ResourceManager.GetString("DocumentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Docs 的本地化字符串。
        /// </summary>
        internal static string DocumentPage {
            get {
                return ResourceManager.GetString("DocumentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DownOnly 的本地化字符串。
        /// </summary>
        internal static string DownOnly {
            get {
                return ResourceManager.GetString("DownOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email 的本地化字符串。
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Examining Patients 的本地化字符串。
        /// </summary>
        internal static string ExaminingPatients {
            get {
                return ResourceManager.GetString("ExaminingPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Cvs 的本地化字符串。
        /// </summary>
        internal static string ExportCvs {
            get {
                return ResourceManager.GetString("ExportCvs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Excel 的本地化字符串。
        /// </summary>
        internal static string ExportExcel {
            get {
                return ResourceManager.GetString("ExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill 的本地化字符串。
        /// </summary>
        internal static string Fill {
            get {
                return ResourceManager.GetString("Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forward 的本地化字符串。
        /// </summary>
        internal static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image 的本地化字符串。
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image 的本地化字符串。
        /// </summary>
        internal static string ImagePage {
            get {
                return ResourceManager.GetString("ImagePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remaining free space for current image storage 的本地化字符串。
        /// </summary>
        internal static string ImageStorageSpaceDes {
            get {
                return ResourceManager.GetString("ImageStorageSpaceDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image storage space 1000/GB 的本地化字符串。
        /// </summary>
        internal static string ImageStorageSpaceTitle {
            get {
                return ResourceManager.GetString("ImageStorageSpaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inspect Records 的本地化字符串。
        /// </summary>
        internal static string InspectRecords {
            get {
                return ResourceManager.GetString("InspectRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsAdmin 的本地化字符串。
        /// </summary>
        internal static string IsAdmin {
            get {
                return ResourceManager.GetString("IsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsSystem 的本地化字符串。
        /// </summary>
        internal static string IsSystem {
            get {
                return ResourceManager.GetString("IsSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 lens Control 的本地化字符串。
        /// </summary>
        internal static string lensControl {
            get {
                return ResourceManager.GetString("lensControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Teach 的本地化字符串。
        /// </summary>
        internal static string LobbyPage {
            get {
                return ResourceManager.GetString("LobbyPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main Screen 的本地化字符串。
        /// </summary>
        internal static string MainScreen {
            get {
                return ResourceManager.GetString("MainScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Memery 的本地化字符串。
        /// </summary>
        internal static string MemeryRate {
            get {
                return ResourceManager.GetString("MemeryRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Memery Rate 的本地化字符串。
        /// </summary>
        internal static string MemeryRateTitle {
            get {
                return ResourceManager.GetString("MemeryRateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Microphone 的本地化字符串。
        /// </summary>
        internal static string Microphone {
            get {
                return ResourceManager.GetString("Microphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mobile： 的本地化字符串。
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monitor 的本地化字符串。
        /// </summary>
        internal static string MonitorPage {
            get {
                return ResourceManager.GetString("MonitorPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name: 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NewFolder 的本地化字符串。
        /// </summary>
        internal static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NormalizedName 的本地化字符串。
        /// </summary>
        internal static string NormalizedName {
            get {
                return ResourceManager.GetString("NormalizedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note: 的本地化字符串。
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The system role has no built-in preset and cannot be deleted or modified! 的本地化字符串。
        /// </summary>
        internal static string NoteInfo {
            get {
                return ResourceManager.GetString("NoteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number： 的本地化字符串。
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Online user statistics 的本地化字符串。
        /// </summary>
        internal static string OnlineUsers {
            get {
                return ResourceManager.GetString("OnlineUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Online 的本地化字符串。
        /// </summary>
        internal static string OnlineUsersTitle {
            get {
                return ResourceManager.GetString("OnlineUsersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Departments 的本地化字符串。
        /// </summary>
        internal static string Org {
            get {
                return ResourceManager.GetString("Org", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Patient 的本地化字符串。
        /// </summary>
        internal static string Patient {
            get {
                return ResourceManager.GetString("Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PatientInformation 的本地化字符串。
        /// </summary>
        internal static string PatientInformation {
            get {
                return ResourceManager.GetString("PatientInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Patient Information Management 的本地化字符串。
        /// </summary>
        internal static string PatientInformationManagement {
            get {
                return ResourceManager.GetString("PatientInformationManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Patient 的本地化字符串。
        /// </summary>
        internal static string PatientPage {
            get {
                return ResourceManager.GetString("PatientPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PermissionCode 的本地化字符串。
        /// </summary>
        internal static string PermissionCode {
            get {
                return ResourceManager.GetString("PermissionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permission Manage 的本地化字符串。
        /// </summary>
        internal static string PermissionManage {
            get {
                return ResourceManager.GetString("PermissionManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permis 的本地化字符串。
        /// </summary>
        internal static string PermissionPage {
            get {
                return ResourceManager.GetString("PermissionPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PermissionType 的本地化字符串。
        /// </summary>
        internal static string PermissionType {
            get {
                return ResourceManager.GetString("PermissionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PhoneNumber 的本地化字符串。
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Picture In Picture 的本地化字符串。
        /// </summary>
        internal static string PictureInPicture {
            get {
                return ResourceManager.GetString("PictureInPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview 的本地化字符串。
        /// </summary>
        internal static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous 的本地化字符串。
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PreviousFolder 的本地化字符串。
        /// </summary>
        internal static string PreviousFolder {
            get {
                return ResourceManager.GetString("PreviousFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print 的本地化字符串。
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RaleName 的本地化字符串。
        /// </summary>
        internal static string RaleName {
            get {
                return ResourceManager.GetString("RaleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recording 的本地化字符串。
        /// </summary>
        internal static string Recording {
            get {
                return ResourceManager.GetString("Recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remarks 的本地化字符串。
        /// </summary>
        internal static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resolution Ratio 的本地化字符串。
        /// </summary>
        internal static string ResolutionRatio {
            get {
                return ResourceManager.GetString("ResolutionRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RoleManage 的本地化字符串。
        /// </summary>
        internal static string RoleManage {
            get {
                return ResourceManager.GetString("RoleManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RoleName 的本地化字符串。
        /// </summary>
        internal static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role 的本地化字符串。
        /// </summary>
        internal static string RolePage {
            get {
                return ResourceManager.GetString("RolePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RolePermission 的本地化字符串。
        /// </summary>
        internal static string RolePermission {
            get {
                return ResourceManager.GetString("RolePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total system running time 的本地化字符串。
        /// </summary>
        internal static string RunTime {
            get {
                return ResourceManager.GetString("RunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run time 的本地化字符串。
        /// </summary>
        internal static string RunTimeTitle {
            get {
                return ResourceManager.GetString("RunTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Screenshot 的本地化字符串。
        /// </summary>
        internal static string Screenshot {
            get {
                return ResourceManager.GetString("Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Screen Stretch Direction 的本地化字符串。
        /// </summary>
        internal static string ScreenStretchDirection {
            get {
                return ResourceManager.GetString("ScreenStretchDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Keywords... 的本地化字符串。
        /// </summary>
        internal static string SearchBox {
            get {
                return ResourceManager.GetString("SearchBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Segment Duration 的本地化字符串。
        /// </summary>
        internal static string SegmentDuration {
            get {
                return ResourceManager.GetString("SegmentDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select/Add Patient 的本地化字符串。
        /// </summary>
        internal static string SelectAddPatient {
            get {
                return ResourceManager.GetString("SelectAddPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select patient to view 的本地化字符串。
        /// </summary>
        internal static string SelectPatientToView {
            get {
                return ResourceManager.GetString("SelectPatientToView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Video Device 的本地化字符串。
        /// </summary>
        internal static string SelectVideoDevice {
            get {
                return ResourceManager.GetString("SelectVideoDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string SettingsPage {
            get {
                return ResourceManager.GetString("SettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sex: 的本地化字符串。
        /// </summary>
        internal static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Picture In Picture 的本地化字符串。
        /// </summary>
        internal static string ShowPictureInPicture {
            get {
                return ResourceManager.GetString("ShowPictureInPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StoragePath: 的本地化字符串。
        /// </summary>
        internal static string StoragePath {
            get {
                return ResourceManager.GetString("StoragePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Control 的本地化字符串。
        /// </summary>
        internal static string SystemControl {
            get {
                return ResourceManager.GetString("SystemControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VCMS视频系统 v1.0.0 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uniform 的本地化字符串。
        /// </summary>
        internal static string Uniform {
            get {
                return ResourceManager.GetString("Uniform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UniformToFill 的本地化字符串。
        /// </summary>
        internal static string UniformToFill {
            get {
                return ResourceManager.GetString("UniformToFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Permission 的本地化字符串。
        /// </summary>
        internal static string UpdatePermission {
            get {
                return ResourceManager.GetString("UpdatePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UploadFiles 的本地化字符串。
        /// </summary>
        internal static string UploadFiles {
            get {
                return ResourceManager.GetString("UploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UploadFolder 的本地化字符串。
        /// </summary>
        internal static string UploadFolder {
            get {
                return ResourceManager.GetString("UploadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UpOnly 的本地化字符串。
        /// </summary>
        internal static string UpOnly {
            get {
                return ResourceManager.GetString("UpOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 URL: 的本地化字符串。
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System user count statistics 的本地化字符串。
        /// </summary>
        internal static string UserCount {
            get {
                return ResourceManager.GetString("UserCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Users 的本地化字符串。
        /// </summary>
        internal static string UserCountTitle {
            get {
                return ResourceManager.GetString("UserCountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UserManage 的本地化字符串。
        /// </summary>
        internal static string UserManage {
            get {
                return ResourceManager.GetString("UserManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UserName 的本地化字符串。
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User 的本地化字符串。
        /// </summary>
        internal static string UserPage {
            get {
                return ResourceManager.GetString("UserPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Video 的本地化字符串。
        /// </summary>
        internal static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Video storage statistics 的本地化字符串。
        /// </summary>
        internal static string VideoCount {
            get {
                return ResourceManager.GetString("VideoCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Video 的本地化字符串。
        /// </summary>
        internal static string VideoManagePage {
            get {
                return ResourceManager.GetString("VideoManagePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Video Recording 的本地化字符串。
        /// </summary>
        internal static string VideoRecording {
            get {
                return ResourceManager.GetString("VideoRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remaining free space for current video storage 的本地化字符串。
        /// </summary>
        internal static string VideoStorageSpaceDes {
            get {
                return ResourceManager.GetString("VideoStorageSpaceDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Video storage space 1000/GB 的本地化字符串。
        /// </summary>
        internal static string VideoStorageSpaceTitle {
            get {
                return ResourceManager.GetString("VideoStorageSpaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View 的本地化字符串。
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View Remark 的本地化字符串。
        /// </summary>
        internal static string ViewRemark {
            get {
                return ResourceManager.GetString("ViewRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VisitNumber: 的本地化字符串。
        /// </summary>
        internal static string VisitNumber {
            get {
                return ResourceManager.GetString("VisitNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VisitTime: 的本地化字符串。
        /// </summary>
        internal static string VisitTime {
            get {
                return ResourceManager.GetString("VisitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome to Dorisoy! 的本地化字符串。
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
